function f = verification_4_phi(x,y,z)
%VERIFICATION_4_PHI
%    F = VERIFICATION_4_PHI(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    03-Sep-2023 11:07:10

f = x.^2+y.^2+z.^2-1.0;
