function f = verification_4_solution(x,y,z)
%VERIFICATION_4_SOLUTION
%    F = VERIFICATION_4_SOLUTION(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    03-Sep-2023 14:33:15

f = [x.^2,y.^2,z.^2];
