function f = verification_3_normal_vector_initial(x,y,z)
%VERIFICATION_3_NORMAL_VECTOR_INITIAL
%    F = VERIFICATION_3_NORMAL_VECTOR_INITIAL(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    01-Sep-2023 08:09:17

t2 = x.^2;
t3 = y.^2;
t4 = t2+t3;
t5 = 1.0./sqrt(t4);
f = [t5.*x,t5.*y,0.0*x];
