function f = verification_5_solution(x,y,z)
%VERIFICATION_5_SOLUTION
%    F = VERIFICATION_5_SOLUTION(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    01-Sep-2023 17:39:16

f = [0.0*x,0.0*x,exp(z)];
