function f = verification_2_normal_vector_initial(x,y,z)
%VERIFICATION_2_NORMAL_VECTOR_INITIAL
%    F = VERIFICATION_2_NORMAL_VECTOR_INITIAL(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    01-Sep-2023 09:17:32

f = [0.0*x,0.0*x,1.0+0.0*x];
