function f = verification_3_phi(x,y,z)
%VERIFICATION_3_PHI
%    F = VERIFICATION_3_PHI(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    01-Sep-2023 08:09:15

f = x.^2+y.^2-1.0;
