function f = verification_1_normal_vector(x,y,z)
%VERIFICATION_1_NORMAL_VECTOR
%    F = VERIFICATION_1_NORMAL_VECTOR(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    02-Sep-2023 13:53:44

t2 = x.^2;
t3 = x.^3;
t5 = y.^2;
t6 = y.^3;
t4 = t2.^2;
t7 = t5.^2;
t8 = t2.*6.4e+1;
t10 = t3.*1.28e+2;
t11 = t5.*6.4e+1;
t13 = t6.*1.28e+2;
t16 = t5.*x.*2.56e+2;
t17 = t2.*y.*2.56e+2;
t24 = t6.*x.*5.12e+2;
t25 = t3.*y.*5.12e+2;
t28 = t2.*t5.*5.12e+2;
t29 = t2.*t6.*5.12e+2;
t30 = t3.*t5.*5.12e+2;
t9 = t4.*6.4e+1;
t12 = t7.*6.4e+1;
t14 = -t10;
t15 = -t13;
t18 = t7.*x.*2.56e+2;
t19 = t4.*y.*2.56e+2;
t20 = -t16;
t21 = -t17;
t26 = t2.*t7.*2.56e+2;
t27 = t4.*t5.*2.56e+2;
t31 = -t29;
t32 = -t30;
t22 = -t18;
t23 = -t19;
t33 = t8+t9+t11+t12+t14+t15+t20+t21+t22+t23+t24+t25+t26+t27+t28+t31+t32+1.0;
t34 = 1.0./sqrt(t33);
f = [t34.*y.*(x.*2.0-1.0).*(y-1.0).*-8.0,t34.*x.*(y.*2.0-1.0).*(x-1.0).*-8.0,t34];
