function f = verification_5_phi(x,y,z)
%VERIFICATION_5_PHI
%    F = VERIFICATION_5_PHI(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Sep-2023 14:58:33

f = z-x.*y;
