function f = verification_5_normal_vector_initial(x,y,z)
%VERIFICATION_5_NORMAL_VECTOR_INITIAL
%    F = VERIFICATION_5_NORMAL_VECTOR_INITIAL(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Sep-2023 14:58:34

t2 = x.^2;
t3 = y.^2;
t4 = t2+t3+1.0;
t5 = 1.0./sqrt(t4);
f = [-t5.*y,-t5.*x,t5];
