function f = verification_2_normal_vector(x,y,z)
%VERIFICATION_2_NORMAL_VECTOR
%    F = VERIFICATION_2_NORMAL_VECTOR(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    01-Sep-2023 08:09:00

t2 = exp(x);
t3 = exp(y);
t4 = x+y;
t6 = x./2.0;
t7 = y./2.0;
t5 = exp(t4);
t8 = exp(t6);
t9 = t2./2.0;
t10 = exp(t7);
t11 = t3./2.0;
t12 = t7+x;
t13 = t6+y;
t19 = t6+t7;
t14 = exp(t12);
t15 = exp(t13);
t16 = t8+2.0;
t17 = t10+2.0;
t18 = t5.*(3.0./1.6e+1);
t20 = exp(t19);
t21 = t14./2.0;
t22 = t15./2.0;
t23 = t8+t9+t10+t11+t18+t20+t21+t22+1.0;
t24 = 1.0./sqrt(t23);
f = [t8.*t17.*t24.*(-1.0./4.0),t10.*t16.*t24.*(-1.0./4.0),(t16.*t17.*t24)./4.0];
