function f = verification_5_normal_vector(x,y,z)
%VERIFICATION_5_NORMAL_VECTOR
%    F = VERIFICATION_5_NORMAL_VECTOR(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    01-Sep-2023 17:39:16

t2 = exp(z);
t3 = x.^2;
t4 = y.^2;
t5 = z.*2.0;
t6 = exp(t5);
t7 = t2+1.0;
t8 = t2.*t3.*2.0;
t9 = t2.*t4.*2.0;
t10 = t3.*t6;
t11 = t4.*t6;
t12 = t3+t4+t8+t9+t10+t11+1.0;
t13 = 1.0./sqrt(t12);
f = [-t7.*t13.*y,-t7.*t13.*x,t13];
