function f = verification_3_solution(x,y,z)
%VERIFICATION_3_SOLUTION
%    F = VERIFICATION_3_SOLUTION(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    02-Sep-2023 14:01:50

t2 = z.^2;
f = [t2.*x,t2.*y,tanh(z)];
