function f = verification_2_phi(x,y,z)
%VERIFICATION_2_PHI
%    F = VERIFICATION_2_PHI(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    01-Sep-2023 09:17:31

f = z;
