function f = verification_4_normal_vector(x,y,z)
%VERIFICATION_4_NORMAL_VECTOR
%    F = VERIFICATION_4_NORMAL_VECTOR(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    03-Sep-2023 14:33:14

t2 = x.*2.0;
t3 = x.^2;
t4 = y.*2.0;
t5 = y.^2;
t6 = z.*2.0;
t7 = z.^2;
t8 = t2+1.0;
t9 = t4+1.0;
t10 = t6+1.0;
t11 = t5.*x.*4.0;
t12 = t3.*y.*4.0;
t13 = t7.*x.*4.0;
t14 = t3.*z.*4.0;
t15 = t7.*y.*4.0;
t16 = t5.*z.*4.0;
t17 = t7.*x.*y.*1.6e+1;
t18 = t5.*x.*z.*1.6e+1;
t19 = t3.*y.*z.*1.6e+1;
t20 = t3.*t5.*8.0;
t21 = t3.*t7.*8.0;
t22 = t5.*t7.*8.0;
t23 = t5.*t7.*x.*3.2e+1;
t24 = t3.*t7.*y.*3.2e+1;
t25 = t3.*t5.*z.*3.2e+1;
t26 = t3.*t5.*t7.*4.8e+1;
t27 = t3+t5+t7+t11+t12+t13+t14+t15+t16+t17+t18+t19+t20+t21+t22+t23+t24+t25+t26;
t28 = 1.0./sqrt(t27);
f = [t9.*t10.*t28.*x,t8.*t10.*t28.*y,t8.*t9.*t28.*z];
