function f = verification_1_phi(x,y,z)
%VERIFICATION_1_PHI
%    F = VERIFICATION_1_PHI(X,Y,Z)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    01-Sep-2023 13:00:28

f = z;
